#! /bin/bash

# All source files.
#clang-format -i $(find . \( -name '*.[hc]' -o -name '*.[hct]pp' \) \! -path '*build*' \! -path '*doxygen*' | sort)

# Only implementation files.
clang-format -i $(find . \( -name '*.c' -o -name '*.[ct]pp' \) \! -path '*build*' \! -path '*doxygen*' | sort)
