name: clang-format-linter
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.13
      with:
        source: 'lib plugins server unit_tests'
        extensions: 'h,hpp,c,cpp,tpp'
        clangFormatVersion: 6
